### ISSUE TITLE
Conda environment creation fails for 2nd Edition also?

### ISSUE THREAD

**Issue by jp-dev** [yhilpisch/py4fi2nd#1]
I noticed there was a similar conda env create issue for the 1st edition's repo.

`conda 4.5.11`

```
conda env create -f py4fi2nd.yml
Using Anaconda API: https://api.anaconda.org
Solving environment: failed

ResolvePackageNotFound:
  - readline=7.0
  - compiler-rt=4.0.1
  - libffi=3.2.1
  - llvm-lto-tapi=4.0.1
  - clang=4.0.1
  - gettext=0.19.8.1
  - dbus=1.13.2
  - mpc=1.1.0
  - ld64=274.2
  - gmp=6.1.2
  - clangxx=4.0.1
  - llvm=4.0.1
  - expat=2.2.6
  - cctools=895
  - libedit=3.1.20170329
  - ptyprocess=0.6.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - clangxx_osx-64=4.0.1
  - glib=2.56.2
  - ncurses=6.1
  - clang_osx-64=4.0.1
  - libgfortran=3.0.1
  - appnope=0.1.0
```

**Comment by yhilpisch** [comment]
The export is from Mac OS and you probably use another OS.

In order to make it work cross-platform, I might need to create a base `yaml` file which explicitly only states the required packages.

**Comment by jp-dev** [comment]
Thanks, you're right. It works perfectly on MacOS. 
I happened to be using Win7 on another PC when I first tested it. I shall close this issue.

**Comment by zoltrader** [comment]
Any solution for Win 10 OS? If not, what do you recommend?

**Comment by yhilpisch** [comment]
The code in the book does really only needs basic packages, such as NumPy, pandas, matplotlib, etc.

You should simply make sure to have these packages installed (which most have anyways on their machines).

Or you use a comprehensive installation such as Anaconda which installs them all at once.
