### ISSUE TITLE
ResolvePackageNotFound:

### ISSUE THREAD

**Issue by untrall** [yhilpisch/py4fi2nd#10]
![image](https://user-images.githubusercontent.com/40770106/131214500-173dbe6c-5838-42e3-b0ac-b70e4c8195bb.png)

**Comment by yhilpisch** [comment]
The YAML file was created on a Mac and might not work (anymore) on Windows.

I recommend you ignore it and work with a standard installation of the "typical" packages (NumPy, pandas, matplotlib, SciPy, etc.).
