### ISSUE TITLE
Docker install: /bin/sh: 1: /install.sh not found

### ISSUE THREAD

**Issue by havarsak** [yhilpisch/py4fi2nd#11]
I've put the Dockerfile and install.sh in an droplet, directory /install/Setup/Docker$
Runs$ sudo docker build -t py4fi:basic .

this goes well, down to Step 5/7, when I get the /bin/sh: 1: /install.sh not found error.

So what's going on? why is Docker looking in bin/sh and not in current directory? It did find /install.sh the moment earlier?

**Comment by JadeChan3** [comment]
Hello！我是香君，恭喜您邮件发送成功，如有需要，我会及时回复您。祝一切安好

**Comment by yhilpisch** [comment]
Are you saying that it worked once but not a second time?

With your description alone it is hard to tell what might go wrong.

**Comment by havarsak** [comment]
![image](https://user-images.githubusercontent.com/95935517/145641460-06662039-e75a-45bf-9c96-d237f6111820.png)

**Comment by havarsak** [comment]
I'm pretty new to linux, so I may be making some really basic mistakes here.

**Comment by havarsak** [comment]
I think I'll try the whole procedure again from scratch :)

**Comment by havarsak** [comment]
Ok, still have the same problem.

I follow the receipe in chapter Using Cloud Instances.
My expected outcome is a fully set up python workspace.

Pre-requisites:
- I have created a droplet on DigitalOcean, and acquired access via ssh, so that I can move files across.
- This is my welcome screen: 
![image](https://user-images.githubusercontent.com/95935517/145725642-a747a6df-1b11-4325-b170-bd8509263893.png)

1. I have updated Jupyter notebook config file with a new password
2. I have put all these install files (install.sh, jupyter_notebook_config.py, reset_droplet.sh, setup.sh) in a folder named cloud under my user
3. using root user, I have run the command bash setup.sh my.ip.address
![image](https://user-images.githubusercontent.com/95935517/145724265-51f66112-0a24-453c-a288-6ed17431b6ea.png)

- the software does not find the files, it seems like a problem finding the IP address?
- No copies of the install files seem to move to the root user folder, so it seems like the first scp command in setup.sh fails
- running root@FirstDrop2:/home/havard/cloud# scp install.sh reset_droplet.sh root@64.227.65.241: results in error message. First, "the authenticity of host cannot be established, do you want to continue". Then, after "yes", the answer is permission denied (publickey)
- I've tried moving the files manually to /root, but it doesn't work either.

**Comment by yhilpisch** [comment]
I think you approach is fundamentally "wrong".

You are already logged into the Droplet and then you try to use the code to setup a Droplet from the Droplet itself.

The code to setup the Droplet is to be executed from your LOCAL machine -- once you have created the Droplet and have the IP available.

I.e. the command `bash setup.sh IP-ADDRESS` is to be executed on your machine to set up the Droplet remotely.

**Comment by havarsak** [comment]
Thanks for a swift answer.
My local machine is windows, so I created a new droplet and ran the code from there
![image](https://user-images.githubusercontent.com/95935517/145986205-39a43899-2b7c-4b73-8463-242ce2577097.png)

Same problem. (I also cant quite understand why it should be impossible to run the command from the same server. And I can't understand what the difference is between running the setup code from a "local" machine or a server)

**Comment by yhilpisch** [comment]
The whole procedure as described in the book and the code examples are designed to be initiated/executed from a LOCAL machine to set up a REMOTE machine. That is why you should follow the instructions and execute the code as described from a local machine and NOT on a Droplet.
