### ISSUE TITLE
Issue creating envirionment using p4fi2nd.yml

### ISSUE THREAD

**Issue by markgahagan1** [yhilpisch/py4fi2nd#15]
I have a linux Mint system and am using latest version of miniconda.

I have followed the installation instructions as per the github page for creating an environment for py4fi2nd.

When I issue the terminal command:
conda env create -f py4fi2nd.yml

I get the following issue:

ResolvePackageNotFound: 
  - libcxxabi=4.0.1
  - clangxx_osx-64=4.0.1
  - clangxx=4.0.1
  - cctools=895
  - libgfortran=3.0.1
  - llvm=4.0.1
  - appnope=0.1.0
  - clang_osx-64=4.0.1
  - libcxx=4.0.1
  - llvm-lto-tapi=4.0.1
  - clang=4.0.1
  - ld64=274.2
  - compiler-rt=4.0.1
The environment is not created.

Do I need to change the yaml file in some way?

Kind Regards

Mark

**Comment by JadeChan3** [comment]
Hello！我是香君，恭喜您邮件发送成功，如有需要，我会及时回复您。祝一切安好

**Comment by markgahagan1** [comment]
Ah! This is a linux issue. I tried it on my Mac and it worked.
