### ISSUE TITLE
Solving enviroment: failed py4fi2nd

### ISSUE THREAD

**Issue by CinderZhang** [yhilpisch/py4fi2nd#16]
**Windows OS
Anaconda installed
Run through Anaconda command line as Administrator**

 R:\py4fi2nd>conda env create -f py4fi2nd.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - dbus=1.13.2
  - libcxxabi=4.0.1
  - libcxx=4.0.1
  - gmp=6.1.2
  - gettext=0.19.8.1
  - cctools=895
  - ncurses=6.1
  - clangxx_osx-64=4.0.1
  - appnope=0.1.0
  - clang_osx-64=4.0.1
  - libedit=3.1.20170329
  - ld64=274.2
  - compiler-rt=4.0.1
  - clang=4.0.1
  - glib=2.56.2
  - llvm=4.0.1
  - libgfortran=3.0.1
  - readline=7.0
  - clangxx=4.0.1
  - llvm-lto-tapi=4.0.1
  - expat=2.2.6

**Comment by JadeChan3** [comment]
Hello！我是香君，恭喜您邮件发送成功，如有需要，我会及时回复您。祝一切安好

**Comment by yhilpisch** [comment]
The yaml file is indeed outdated and was originally created on MacOS.

I recommend creating an environment with just the standard packages, such as numpy, pandas, matlotlib, etc. This should work for most parts of the book out-of-the-box.
