### ISSUE TITLE
where can download the pylab model?

### ISSUE THREAD

**Issue by GavinMoreYoung** [yhilpisch/py4fi2nd#2]
i see the issue on working code
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-04b4b222c82d> in <module>
      1 import numpy as np
      2 import pandas as pd
----> 3 from pylab import plt, mpl
      4 plt.style.use('seaborn')
      5 mpl.rcParams['font.family'] = 'serif'
ModuleNotFoundError: No module named 'pylab'
could you can tell me where can download the module? thank you.

**Comment by yhilpisch** [comment]
`pylab` is part of `matplotlib`.

Therefore install it eg via

`pip install matplotlib`

**Comment by GavinMoreYoung** [comment]
> `pylab`是的一部分`matplotlib`。
> 
> 因此，例如通过安装它
> 
> `pip install matplotlib`

thank you very much,
