### ISSUE TITLE
couldn't install yaml

### ISSUE THREAD

**Issue by zhghao** [yhilpisch/py4fi2nd#4]
I am using Anaconda 4.7.10, and couldn't install the env from yaml

Here is the message

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - libgfortran=3.0.1
  - cctools=895
  - libcxxabi=4.0.1
  - appnope=0.1.0
  - libffi=3.2.1
  - clangxx_osx-64=4.0.1
  - glib=2.56.2
  - llvm-lto-tapi=4.0.1
  - expat=2.2.6
  - gettext=0.19.8.1
  - ld64=274.2
  - clang=4.0.1
  - libedit=3.1.20170329
  - ncurses=6.1
  - dbus=1.13.2
  - clang_osx-64=4.0.1
  - llvm=4.0.1
  - gmp=6.1.2
  - libcxx=4.0.1
  - clangxx=4.0.1
  - mpc=1.1.0
  - compiler-rt=4.0.1
  - readline=7.0
  - ptyprocess=0.6.0

**Comment by yhilpisch** [comment]
What platform are you on? My exports have been from MacOS.

**Comment by zhghao** [comment]
WIN10.

**Comment by yhilpisch** [comment]
I am afraid but I do not have a yaml file for Windows.

It should be easy enough to just install the single standard packages (numpy, pandas, matplotlib, etc.).
