### ISSUE TITLE
Help on Chapter 17 

### ISSUE THREAD

**Issue by crm2730** [yhilpisch/py4fi2nd#6]
Hello. I was hoping to get help on a error that I cannot figure out. The code is as follows:

---------------------------------------------------------------------------------------
[1]
import numpy as np
import pandas as pd
import datetime as dt

[2]
from pylab import mpl, plt
plt.style.use('seaborn')
mpl.rcParams['font.family'] = 'serif'
%matplotlib inline

[3]
import sys
sys.path.append(r'C:\Users\****\dx-master\dx')
#I was getting an error without 'r' in front of C

[4]
dates = [dt.datetime(2020, 1, 1), dt.datetime(2020, 7, 1),
               dt.datetime(2021, 1, 1)]

[5]
(dates[1] - dates[0]).days / 365.
    Out:0.4986301369863014

[6]
(dates[2] - dates[1]).days / 365.
    Out:0.5041095890410959

[7]
fractions = [0.0, 0.5, 1.0]

#
#DX Package
#
#Frame -- Helper Function
#
#get_year_deltas.py
#
#Python for Finance, 2nd ed.
#(c) Dr. Yvess J. Hilpisch
#
import numpy as np

def get_year_deltas(date_list, day_count=365.):
    ''' Return vector of floats with day deltas in years.
    Initial value normalized to zero.
   
   Parameters
    ==========
    date_list : list or array
        collection of datetime objects
    day_count : float
        number of days for a year
        (to account for different conventions)
    
    Results
    =======
    delta_list : array
        year fractions
    '''

    start = date_list[0]
    delta_list = [(date - start).days / day_count
                  for date in date_list]
    return np.array(delta_list)

[8]
from get_year_deltas import get_year_deltas

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-38-b9aabebb1280> in <module>
----> 1 from get_year_deltas import get_year_deltas

ModuleNotFoundError: No module named 'get_year_deltas'

----------------------------------------------------------------------------------

I cant seem to figure out why the module isnt being found. Any help would be appreciated.

**Comment by yhilpisch** [comment]
What is the contents of your **dx** folder?

Is it the same as in the one as seen here?

https://github.com/yhilpisch/py4fi2nd/tree/master/code/dx

**Comment by crm2730** [comment]
I got the contents of that dx folder from https://github.com/yhilpisch/dx under the "clone or download" hyperlink which didn't have a few key codes. After getting all of those from the link you sent I was able to resolve the error. Thank you for your help and I am really enjoying the book. Thanks again.
