### ISSUE TITLE
.yml - Solving environment failed

### ISSUE THREAD

**Issue by joe-wojniak** [yhilpisch/py4fi2nd#8]
i could use some help with the following error message. i'm on a Windows7 system running anaconda3.

when i run the following command in a conda window to setup the py4fi2nd environment, i get the following:
```
\py4fi2nd\>conda env create -f py4fi2nd.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
- ncurses=6.1
- glib-2.56.2
-compiler-rt=4.0.1
... (long list of packages)
-clang_osx-64=4.0.1
-gmp=6.1.2
-readline=7.0
```
thanks for any suggestions that might help.  i'm open to modifying the .yml file if it needs to be customized for Windows, for example- clang_osx-64=4.0.1 is probably for MacOS?

Or, I can import the libraries to the env as needed.

-jw

**Comment by yhilpisch** [comment]
It probably is outdated anyway. You should rather install the few packages used manually.

There are not too many. Mostly standard ones are used, such as NumPy, pandas, matplotlib, etc.
